### ISSUE TITLE
building fails on mac osx

### ISSUE THREAD

**Issue by vcsync** [varnishcache/testrepo2#49]
I'm trying to get it to build on my mac (osx, 10.4), but it fails halfway the Make step.

Where it starts to fail:

```
Making all in varnishd
if gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../../include   -include config.h -O2 -pipe -Wall -Wno-unused-parameter -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wcast-qual -Wwrite-strings -Wswitch -Wshadow -Wcast-align -Wunused-parameter -Wchar-subscripts -Winline -Wnested-externs -Wredundant-decls -Wformat -O -g -fno-inline -MT varnishd-cache_acceptor.o -MD -MP -MF ".deps/varnishd-cache_acceptor.Tpo" -c -o varnishd-cache_acceptor.o `test -f 'cache_acceptor.c' || echo './'`cache_acceptor.c; \
then mv -f ".deps/varnishd-cache_acceptor.Tpo" ".deps/varnishd-cache_acceptor.Po"; else rm -f ".deps/varnishd-cache_acceptor.Tpo"; exit 1; fi
cache_acceptor.c: In function 'vca_acct':
cache_acceptor.c:170: warning: implicit declaration of function 'clock_gettime'
cache_acceptor.c:170: warning: nested extern declaration of 'clock_gettime'
cache_acceptor.c:170: error: 'CLOCK_REALTIME' undeclared (first use in this function)
cache_acceptor.c:170: error: (Each undeclared identifier is reported only once
cache_acceptor.c:170: error: for each function it appears in.)
{standard input}:375:non-relocatable subtraction expression, "_tv_rcvtimeo" minus "L00000000002$pb"
{standard input}:375:symbol: "_tv_rcvtimeo" can't be undefined in a subtraction expression
{standard input}:374:non-relocatable subtraction expression, "_tv_rcvtimeo" minus "L00000000002$pb"
{standard input}:374:symbol: "_tv_rcvtimeo" can't be undefined in a subtraction expression
{standard input}:366:non-relocatable subtraction expression, "_need_rcvtimeo" minus "L00000000002$pb"

......

{standard input}:100:symbol: "_need_linger" can't be undefined in a subtraction expression
{standard input}:93:non-relocatable subtraction expression, "_linger" minus "L00000000001$pb"
{standard input}:93:symbol: "_linger" can't be undefined in a subtraction expression
{standard input}:92:non-relocatable subtraction expression, "_linger" minus "L00000000001$pb"
{standard input}:92:symbol: "_linger" can't be undefined in a subtraction expression
make[3]: *** [varnishd-cache_acceptor.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

I ran configure with the recommended "./configure --enable-debugging-symbols --enable-developer-warnings --prefix=/opt/varnish".

Any other input that's needed?

**Comment by vcsync** [comment]
This is a known issue.  The solution is to

 * use gettimeofday() instead of clock_gettime() when the latter is not available
 * bug the hell out of Apple; clock_gettime() is required by POSIX.

**Comment by vcsync** [comment]
i replaced all occurances of clock_gettime with gettimeofday but it's still failing.


```
Making all in varnishd
if gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../../include   -include config.h -O2 -pipe -Wall -Wno-unused-parameter -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wcast-qual -Wwrite-strings -Wswitch -Wshadow -Wcast-align -Wunused-parameter -Wchar-subscripts -Winline -Wnested-externs -Wredundant-decls -Wformat -O -g -fno-inline -MT varnishd-cache_acceptor.o -MD -MP -MF ".deps/varnishd-cache_acceptor.Tpo" -c -o varnishd-cache_acceptor.o `test -f 'cache_acceptor.c' || echo './'`cache_acceptor.c; \
then mv -f ".deps/varnishd-cache_acceptor.Tpo" ".deps/varnishd-cache_acceptor.Po"; else rm -f ".deps/varnishd-cache_acceptor.Tpo"; exit 1; fi
cache_acceptor.c: In function ‘vca_acct’:
cache_acceptor.c:170: error: ‘CLOCK_REALTIME’ undeclared (first use in this function)
cache_acceptor.c:170: error: (Each undeclared identifier is reported only once
cache_acceptor.c:170: error: for each function it appears in.)
cache_acceptor.c:170: warning: passing argument 2 of ‘gettimeofday’ from incompatible pointer type
{standard input}:398:non-relocatable subtraction expression, "_tv_rcvtimeo" minus "L00000000002$pb"
{standard input}:398:symbol: "_tv_rcvtimeo" can't be undefined in a subtraction expression
{standard input}:394:non-relocatable subtraction expression, "_need_rcvtimeo" minus "L00000000002$pb"
{standard input}:394:symbol: "_need_rcvtimeo" can't be undefined in a subtraction expression
{standard input}:371:non-relocatable subtraction expression, "_tv_sndtimeo" minus "L00000000002$pb"
{standard input}:371:symbol: "_tv_sndtimeo" can't be undefined in a subtraction expression
{standard input}:367:non-relocatable subtraction expression, "_need_sndtimeo" minus "L00000000002$pb"
{standard input}:367:symbol: "_need_sndtimeo" can't be undefined in a subtraction expression
{standard input}:344:non-relocatable subtraction expression, "_linger" minus "L00000000002$pb"
{standard input}:344:symbol: "_linger" can't be undefined in a subtraction expression
{standard input}:340:non-relocatable subtraction expression, "_need_linger" minus "L00000000002$pb"
{standard input}:340:symbol: "_need_linger" can't be undefined in a subtraction expression
{standard input}:332:non-relocatable subtraction expression, "_need_test" minus "L00000000002$pb"
{standard input}:332:symbol: "_need_test" can't be undefined in a subtraction expression
{standard input}:237:non-relocatable subtraction expression, "_need_linger" minus "L00000000001$pb"
{standard input}:237:symbol: "_need_linger" can't be undefined in a subtraction expression
{standard input}:235:non-relocatable subtraction expression, "_need_sndtimeo" minus "L00000000001$pb"
{standard input}:235:symbol: "_need_sndtimeo" can't be undefined in a subtraction expression
{standard input}:231:non-relocatable subtraction expression, "_need_test" minus "L00000000001$pb"
{standard input}:231:symbol: "_need_test" can't be undefined in a subtraction expression
{standard input}:229:non-relocatable subtraction expression, "_need_rcvtimeo" minus "L00000000001$pb"
{standard input}:229:symbol: "_need_rcvtimeo" can't be undefined in a subtraction expression
{standard input}:226:non-relocatable subtraction expression, "_need_rcvtimeo" minus "L00000000001$pb"
{standard input}:226:symbol: "_need_rcvtimeo" can't be undefined in a subtraction expression
{standard input}:212:non-relocatable subtraction expression, "_tv_rcvtimeo" minus "L00000000001$pb"
{standard input}:212:symbol: "_tv_rcvtimeo" can't be undefined in a subtraction expression
{standard input}:168:non-relocatable subtraction expression, "_need_sndtimeo" minus "L00000000001$pb"
{standard input}:168:symbol: "_need_sndtimeo" can't be undefined in a subtraction expression
{standard input}:165:non-relocatable subtraction expression, "_need_sndtimeo" minus "L00000000001$pb"
{standard input}:165:symbol: "_need_sndtimeo" can't be undefined in a subtraction expression
{standard input}:151:non-relocatable subtraction expression, "_tv_sndtimeo" minus "L00000000001$pb"
{standard input}:151:symbol: "_tv_sndtimeo" can't be undefined in a subtraction expression
{standard input}:107:non-relocatable subtraction expression, "_need_linger" minus "L00000000001$pb"
{standard input}:107:symbol: "_need_linger" can't be undefined in a subtraction expression
{standard input}:104:non-relocatable subtraction expression, "_need_linger" minus "L00000000001$pb"
{standard input}:104:symbol: "_need_linger" can't be undefined in a subtraction expression
{standard input}:90:non-relocatable subtraction expression, "_linger" minus "L00000000001$pb"
{standard input}:90:symbol: "_linger" can't be undefined in a subtraction expression
make[3]: *** [varnishd-cache_acceptor.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by vcsync** [comment]
hi there :) any news. i'm really keen to get this running for developing zope3 integration on my machine.

**Comment by vcsync** [comment]
Fixed in trunk last week (r1145, r1146)

**Comment by vcsync** [comment]
For the record: updated instructions for Mac OS X can be found in the [wiki:Installation wiki] now.
